-- Batch 2: Craft & Structure - Part 1 (Word Meaning - 12 questions)

INSERT INTO sat_questions (domain, question_type, difficulty, question_text, passage_text, choices, correct_answer, explanation, tags) VALUES

('Craft & Structure', 'mcq', 'easy',
'As used in line 3, novel most nearly means',
'The research teams approach to treating the disease was novel, diverging significantly from conventional methods. Rather than targeting the pathogen directly, they focused on strengthening the immune systems natural defenses. This innovative strategy had never been attempted at such a large scale.',
'{"A": "fictional", "B": "new", "C": "lengthy", "D": "literary"}',
'B',
'{"rationale": "In this context, novel means new or innovative. The passage describes the approach as diverging from conventional methods and never attempted before, which reinforces the meaning of new or original.", "why_others_wrong": {"A": "Novel can mean a fiction book, but context clearly indicates new/innovative", "C": "Lengthy has no connection to the passage meaning", "D": "Literary relates to novels as books, not the intended meaning here"}}',
ARRAY['word-meaning', 'vocabulary-in-context', 'multiple-meanings']),

('Craft & Structure', 'mcq', 'easy',
'In line 5, the word regime most nearly means',
'The new medication regime requires patients to take three pills daily with meals. Adherence to this schedule is critical for the treatment to be effective. Skipping doses or taking medication irregularly can significantly reduce therapeutic benefits.',
'{"A": "government", "B": "system", "C": "punishment", "D": "overthrow"}',
'B',
'{"rationale": "Regime here refers to a systematic plan or schedule of medication. The context of taking pills daily with meals indicates a structured system or routine, not a political government.", "why_others_wrong": {"A": "Regime can mean government, but context is medical treatment", "C": "No punitive context appears", "D": "Refers to government overthrow, completely irrelevant here"}}',
ARRAY['word-meaning', 'medical-context', 'vocabulary']),

('Craft & Structure', 'mcq', 'medium',
'As used in line 8, charged most nearly means',
'The political rally was charged with tension as opposing groups faced each other across police barricades. Speakers voices grew louder and more heated with each passing moment. The atmosphere felt electric, as if violence could erupt at any second.',
'{"A": "accused", "B": "filled", "C": "billed", "D": "rushed"}',
'B',
'{"rationale": "Charged here means filled or infused with emotion/energy. The passage describes tension, heated voices, and an electric atmosphere, indicating the environment was filled with emotional intensity.", "why_others_wrong": {"A": "Accused fits legal contexts, not atmospheric description", "C": "Billed relates to payment, irrelevant here", "D": "Rushed means moved quickly, does not fit the tense atmosphere description"}}',
ARRAY['word-meaning', 'figurative-language', 'connotation']),

('Craft & Structure', 'mcq', 'medium',
'The word sanguine in line 12 most closely means',
'Despite mounting evidence of economic challenges, the CEO remained sanguine about the companys prospects. She pointed to strong customer loyalty and innovative products currently in development. Her optimistic outlook contrasted sharply with analysts more cautious assessments.',
'{"A": "bloody", "B": "optimistic", "C": "realistic", "D": "indifferent"}',
'B',
'{"rationale": "Sanguine means optimistic or positive. The passage explicitly states the CEOs optimistic outlook and contrasts it with more cautious views, directly supporting this meaning.", "why_others_wrong": {"A": "Sanguine etymologically relates to blood, but modern usage means optimistic", "C": "Her view contrasts with realistic/cautious analysts", "D": "She actively holds positive views, not indifference"}}',
ARRAY['word-meaning', 'advanced-vocabulary', 'business-context']),

('Craft & Structure', 'mcq', 'medium',
'As used in line 6, tempered most nearly means',
'The scientists initial enthusiasm was tempered by the studys limitations. While results showed promise, the small sample size and short duration meant conclusions had to remain tentative. Further research would be necessary to confirm these preliminary findings.',
'{"A": "strengthened", "B": "moderated", "C": "heated", "D": "ruined"}',
'B',
'{"rationale": "Tempered means moderated or restrained. The enthusiasm was lessened or qualified by limitations, requiring tentative conclusions rather than strong claims.", "why_others_wrong": {"A": "Opposite meaning—enthusiasm was reduced, not strengthened", "C": "Temper can relate to heat in metallurgy, but not this context", "D": "Too extreme—enthusiasm was moderated, not destroyed"}}',
ARRAY['word-meaning', 'nuance', 'scientific-writing']),

('Craft & Structure', 'mcq', 'hard',
'In context, wanting in line 9 means',
'The committees review found the proposal wanting in several critical areas. Budget projections lacked supporting data. Implementation timelines appeared unrealistic. Risk assessment was superficial at best. These deficiencies would need to be addressed before the project could receive approval.',
'{"A": "desiring", "B": "needing", "C": "deficient", "D": "requesting"}',
'C',
'{"rationale": "Wanting means deficient or lacking in quality. The passage lists multiple deficiencies and inadequacies in the proposal, directly supporting this meaning.", "why_others_wrong": {"A": "Wanting can mean desiring, but context describes inadequacy not desire", "B": "Close but wanting means lacking quality, not just needing something", "D": "Requesting is unrelated to the context of inadequacy"}}',
ARRAY['word-meaning', 'archaic-usage', 'formal-writing']),

('Craft & Structure', 'mcq', 'hard',
'The word pedestrian in line 14 most nearly means',
'Critics dismissed the authors latest work as pedestrian, lacking the creative spark that characterized her earlier novels. The plot followed predictable patterns, characters felt generic, and prose lacked stylistic innovation. It was competent but unremarkable writing that failed to challenge or surprise readers.',
'{"A": "walking", "B": "ordinary", "C": "dangerous", "D": "formal"}',
'B',
'{"rationale": "Pedestrian as an adjective means ordinary or unimaginative. The context of lacking creativity, following predictable patterns, and being unremarkable all support this meaning of commonplace or dull.", "why_others_wrong": {"A": "Pedestrian as noun means walker, but used as adjective here", "C": "No connection to danger in literary criticism context", "D": "Formality is not discussed; issue is lack of creativity"}}',
ARRAY['word-meaning', 'literary-criticism', 'secondary-meanings']),

('Craft & Structure', 'mcq', 'hard',
'As used in line 11, economy most nearly means',
'The poets economy of language was masterful—every word served a purpose, nothing was superfluous. Where lesser writers might use a dozen words, she used three. This conciseness gave her work remarkable power and clarity.',
'{"A": "financial system", "B": "thriftiness", "C": "efficiency", "D": "poverty"}',
'C',
'{"rationale": "Economy here means efficiency or conciseness in use of language. The passage emphasizes how every word served a purpose with no excess, demonstrating efficient use of words.", "why_others_wrong": {"A": "Economic system is irrelevant to literary analysis", "B": "Thriftiness is close but economy emphasizes efficiency not just saving", "D": "Poverty has no connection to the passages meaning"}}',
ARRAY['word-meaning', 'literary-analysis', 'precise-diction']),

('Craft & Structure', 'mcq', 'easy',
'In line 7, the word distinguished most nearly means',
'The distinguished professor had published over 100 papers and mentored dozens of successful students during her 40-year career. Her contributions to molecular biology earned her numerous awards, including election to the National Academy of Sciences.',
'{"A": "separated", "B": "eminent", "C": "noticed", "D": "different"}',
'B',
'{"rationale": "Distinguished means eminent or renowned. The professors extensive publications, successful mentoring, and major awards all indicate high reputation and eminence in her field.", "why_others_wrong": {"A": "Distinguish can mean separate, but context shows reputation not separation", "C": "Too weak—noticed does not capture the high level of achievement described", "D": "Different is unrelated to the context of professional achievement"}}',
ARRAY['word-meaning', 'academic-context', 'professional-description']),

('Craft & Structure', 'mcq', 'medium',
'The word appreciate in line 10 most closely means',
'Real estate in the neighborhood continued to appreciate steadily over the decade. Property values increased an average of 8 percent annually. Homeowners who purchased in 2010 saw their investments more than double by 2020.',
'{"A": "be grateful for", "B": "understand", "C": "increase in value", "D": "admire"}',
'C',
'{"rationale": "Appreciate in financial context means increase in value. The passage discusses property values increasing and investments doubling, clearly indicating financial appreciation.", "why_others_wrong": {"A": "Gratitude is unrelated to property value discussion", "B": "Understanding is not discussed; focus is on value changes", "D": "Admiration is irrelevant to real estate value context"}}',
ARRAY['word-meaning', 'financial-terminology', 'context-dependent']),

('Craft & Structure', 'mcq', 'hard',
'As used in line 13, plastic most nearly means',
'The young childs personality was still plastic, easily shaped by experiences and relationships. Early interventions could have profound effects that would be much harder to achieve once behavioral patterns became more firmly established in adolescence.',
'{"A": "synthetic", "B": "flexible", "C": "artificial", "D": "credit card"}',
'B',
'{"rationale": "Plastic here means flexible or malleable. The passage describes personality as easily shaped by experiences, emphasizing adaptability before patterns become fixed—classic use of plastic meaning moldable.", "why_others_wrong": {"A": "Synthetic material is unrelated to personality development", "C": "Artificial implies fake, not the intended meaning of malleable", "D": "Payment method is completely irrelevant"}}',
ARRAY['word-meaning', 'psychological-terminology', 'technical-usage']),

('Craft & Structure', 'mcq', 'hard',
'The word sanction in line 15 most nearly means',
'The international organization refused to sanction the proposed military intervention. Without explicit approval, member nations would act outside established protocols. The decision reflected deep divisions about appropriate responses to the crisis.',
'{"A": "punish", "B": "approve", "C": "criticize", "D": "ignore"}',
'B',
'{"rationale": "Sanction here means approve or authorize. The passage discusses refusing to give explicit approval and acting outside established protocols, indicating sanction means official authorization. Note: sanction can also mean punish, but context determines which meaning applies.", "why_others_wrong": {"A": "Sanction can mean punish, but context clearly indicates authorization not punishment", "C": "Criticize is not a meaning of sanction", "D": "Ignore is unrelated to the concept of official approval"}}',
ARRAY['word-meaning', 'contronyms', 'political-context']);