-- Add all remaining Section B and C questions for AQA Geography A-level Paper 1

-- Section B: Hot Desert Systems (4 questions, 36 marks total: 2+4+6+24)
INSERT INTO curriculum_questions (id, topic_id, question, marks, difficulty, model_answer, marking_criteria, spec_reference, order_index) VALUES
('geo-paper1-2a', 'hot-desert-systems', 'Define the term sediment budget.', 2, 'easy', 'A sediment budget is the balance between sediment inputs (sources), transfers (flows), and outputs (sinks) within a system.', '{"2_marks":["Clear definition","Reference to inputs and outputs"]}', 'AQA 3.2.2.1', 100),
('geo-paper1-2b', 'hot-desert-systems', 'Outline one process that transfers sediment within hot desert environments.', 4, 'easy', 'Saltation is a key process. Wind picks up sand grains and bounces them along the surface in a series of jumps or hops.', '{"1_mark":["Names process"],"4_marks":["Full explanation with detail"]}', 'AQA 3.2.2.2', 101),
('geo-paper1-2c', 'hot-desert-systems', 'Explain how physical processes shape landforms in hot desert settings.', 6, 'medium', 'Weathering breaks down rocks, wind erosion creates yardangs, saltation moves sand to form dunes (barchan, seif), and flash floods carve wadis and deposit alluvial fans.', '{"3-4_marks":["Two processes explained"],"5-6_marks":["Multiple processes with named landforms"]}', 'AQA 3.2.2', 102),
('geo-paper1-2d', 'hot-desert-systems', 'Evaluate how climate change contributes to desertification in hot desert systems.', 24, 'hard', 'Climate change increases temperatures and alters precipitation, but human factors like overgrazing remain dominant. Both interact as threat multipliers.', '{"13-18_marks":["Detailed climate mechanisms with examples"],"19-24_marks":["Critical evaluation of climate vs human factors"]}', 'AQA 3.2.2.5', 103),

-- Section B: Coastal Systems (4 questions, 36 marks total: 2+4+6+24)
('geo-paper1-2a-coastal', 'coastal-systems', 'Define the term sediment budget.', 2, 'easy', 'A sediment budget is the balance between sediment inputs, transfers, and outputs in a coastal system.', '{"2_marks":["Clear definition","Reference to balance"]}', 'AQA 3.2.3.1', 104),
('geo-paper1-2b-coastal', 'coastal-systems', 'Outline one process that transfers sediment within coastal environments.', 4, 'easy', 'Longshore drift moves sediment along the coast. Waves approach at an angle, pushing material up the beach in the swash, then gravity pulls it straight down in the backwash.', '{"1_mark":["Names longshore drift"],"4_marks":["Full explanation of swash and backwash"]}', 'AQA 3.2.3.2', 105),
('geo-paper1-2c-coastal', 'coastal-systems', 'Explain how physical processes shape landforms in coastal settings.', 6, 'medium', 'Marine erosion (hydraulic action, abrasion) creates cliffs and wave-cut platforms. Longshore drift transports sediment to form spits and bars. Deposition creates beaches.', '{"3-4_marks":["Two processes"],"5-6_marks":["Multiple processes with named landforms"]}', 'AQA 3.2.3', 106),
('geo-paper1-2d-coastal', 'coastal-systems', 'Evaluate how climate change contributes to changes in coastal landforms.', 24, 'hard', 'Sea level rise increases erosion and flooding. Storm intensity changes affect wave energy. Both alter sediment budgets and accelerate coastal change.', '{"13-18_marks":["Climate mechanisms with examples"],"19-24_marks":["Comprehensive evaluation with case studies"]}', 'AQA 3.2.3.5', 107),

-- Section B: Glacial Systems (4 questions, 36 marks total: 2+4+6+24)
('geo-paper1-2a-glacial', 'glacial-systems', 'Define the term sediment budget.', 2, 'easy', 'A sediment budget is the balance between inputs, transfers, and outputs of sediment within a glacial system.', '{"2_marks":["Clear definition","Reference to balance"]}', 'AQA 3.2.4.1', 108),
('geo-paper1-2b-glacial', 'glacial-systems', 'Outline one process that transfers sediment within glacial environments.', 4, 'easy', 'Glaciers transport debris through basal sliding and ice deformation. Material is carried on, within, or beneath the ice as supraglacial, englacial, or subglacial debris.', '{"1_mark":["Names transport process"],"4_marks":["Full explanation with debris types"]}', 'AQA 3.2.4.2', 109),
('geo-paper1-2c-glacial', 'glacial-systems', 'Explain how physical processes shape landforms in glacial settings.', 6, 'medium', 'Glacial erosion (plucking, abrasion) creates corries and U-shaped valleys. Deposition forms moraines and drumlins. Meltwater creates eskers and outwash plains.', '{"3-4_marks":["Two processes"],"5-6_marks":["Multiple processes with named landforms"]}', 'AQA 3.2.4', 110),
('geo-paper1-2d-glacial', 'glacial-systems', 'Evaluate how climate change contributes to glacial retreat and associated landforms.', 24, 'hard', 'Rising temperatures accelerate melting, causing glacier retreat. This exposes new landforms (moraines) and increases meltwater erosion and deposition.', '{"13-18_marks":["Climate mechanisms with examples"],"19-24_marks":["Comprehensive evaluation with case studies"]}', 'AQA 3.2.4.5', 111),

-- Section C: Hazards (5 questions, 48 marks total: 2+4+6+12+24)
('geo-paper1-3a-hazards', 'hazards', 'Define the term resilience.', 2, 'easy', 'Resilience is the ability of a community or system to absorb, adapt to, and recover from the impacts of a hazard event.', '{"2_marks":["Clear definition","Reference to recovery"]}', 'AQA 3.2.6.1', 112),
('geo-paper1-3b-hazards', 'hazards', 'Outline one natural factor influencing hazard impacts.', 4, 'easy', 'Magnitude determines the severity of impacts. Higher magnitude earthquakes or storms cause more extensive damage, casualties, and economic losses.', '{"1_mark":["Names factor"],"4_marks":["Full explanation with examples"]}', 'AQA 3.2.6.2', 113),
('geo-paper1-3c-hazards', 'hazards', 'Explain how human activity influences the impacts of volcanic or seismic events.', 6, 'medium', 'Building quality, land use planning, and population density affect vulnerability. Poor construction increases casualties. Dense urban areas concentrate damage. Preparedness and monitoring reduce impacts.', '{"3-4_marks":["Two factors explained"],"5-6_marks":["Multiple factors with examples"]}', 'AQA 3.2.6.3', 114),
('geo-paper1-3d-hazards', 'hazards', 'Assess the effectiveness of management strategies used in seismic or volcanic hazard management.', 12, 'medium', 'Prediction and monitoring save lives (Japan seismic networks). Engineering (base isolation) reduces damage. Education increases preparedness. However, costs limit implementation in LICs.', '{"7-9_marks":["Multiple strategies with examples"],"10-12_marks":["Critical assessment with strengths and limitations"]}', 'AQA 3.2.6.4', 115),
('geo-paper1-3e-hazards', 'hazards', 'Evaluate how global environmental change affects hazard frequency and severity at different scales.', 24, 'hard', 'Climate change increases tropical storm intensity and alters precipitation patterns, affecting floods and droughts. Rising sea levels amplify coastal hazards. Scale varies from local to global impacts.', '{"13-18_marks":["Detailed mechanisms with scale"],"19-24_marks":["Comprehensive multi-scale evaluation with evidence"]}', 'AQA 3.2.6.5', 116),

-- Section C: Ecosystems Under Stress (5 questions, 48 marks total: 2+4+6+12+24)
('geo-paper1-3a-eco', 'ecosystems-under-stress', 'Define the term resilience.', 2, 'easy', 'Resilience is the ability of an ecosystem to absorb disturbances, adapt, and maintain its essential functions and structures.', '{"2_marks":["Clear definition","Reference to adaptation"]}', 'AQA 3.2.7.1', 117),
('geo-paper1-3b-eco', 'ecosystems-under-stress', 'Outline one natural factor influencing ecosystem stability.', 4, 'easy', 'Biodiversity enhances stability. Greater species diversity provides functional redundancy, so if one species declines, others can fulfill similar roles.', '{"1_mark":["Names biodiversity"],"4_marks":["Full explanation of mechanism"]}', 'AQA 3.2.7.2', 118),
('geo-paper1-3c-eco', 'ecosystems-under-stress', 'Explain how human activity affects nutrient and carbon cycles within ecosystems.', 6, 'medium', 'Deforestation disrupts carbon storage and nutrient cycling. Agriculture adds fertilizers, causing eutrophication. Burning fossil fuels increases atmospheric carbon, affecting NPP.', '{"3-4_marks":["Two impacts explained"],"5-6_marks":["Multiple impacts with cycle connections"]}', 'AQA 3.2.7.3', 119),
('geo-paper1-3d-eco', 'ecosystems-under-stress', 'Assess the effectiveness of management strategies to conserve fragile ecosystems.', 12, 'medium', 'Protected areas (national parks) preserve biodiversity. Sustainable management (selective logging) balances use and conservation. Community involvement increases success. Limitations include funding and enforcement.', '{"7-9_marks":["Multiple strategies with examples"],"10-12_marks":["Critical assessment with strengths and limitations"]}', 'AQA 3.2.7.4', 120),
('geo-paper1-3e-eco', 'ecosystems-under-stress', 'Evaluate how global environmental change affects ecosystem resilience at different scales.', 24, 'hard', 'Climate change alters species distributions and phenology. Temperature rise stresses coral reefs. Precipitation changes affect rainforest function. Local to global scales show varying impacts and adaptive capacity.', '{"13-18_marks":["Detailed mechanisms across scales"],"19-24_marks":["Comprehensive multi-scale evaluation with evidence"]}', 'AQA 3.2.7.5', 121)