-- Batch 1: Information & Ideas - Part 4 (Data Interpretation - 12 questions, completing batch 1)

INSERT INTO sat_questions (domain, question_type, difficulty, question_text, passage_text, choices, correct_answer, explanation, tags) VALUES

('Information & Ideas', 'mcq', 'easy',
'According to the table, which age group had the highest voter turnout in the 2020 election?',
'A study analyzing voter turnout in the 2020 US presidential election found significant variation across age groups. The data revealed that 18-29 year olds had a turnout rate of 53 percent, 30-44 year olds reached 62 percent, 45-64 year olds achieved 69 percent, and those 65 and older had the highest turnout at 74 percent. These patterns have remained relatively consistent across recent elections, with older voters participating at higher rates than younger demographics.',
'{"A": "18-29 year olds", "B": "30-44 year olds", "C": "45-64 year olds", "D": "65 and older"}',
'D',
'{"rationale": "The passage explicitly states that those 65 and older had the highest turnout at 74 percent, which exceeds all other age groups percentages.", "why_others_wrong": {"A": "18-29 had the lowest at 53 percent", "B": "30-44 had 62 percent, not the highest", "C": "45-64 had 69 percent, second highest but not the highest"}}',
ARRAY['data-interpretation', 'statistics', 'civic-engagement']),

('Information & Ideas', 'mcq', 'easy',
'Based on the data presented, what trend is evident regarding renewable energy adoption?',
'Between 2010 and 2023, global renewable energy capacity underwent dramatic expansion. Solar capacity increased from 40 gigawatts to 1,200 gigawatts. Wind capacity grew from 198 gigawatts to 1,000 gigawatts. Hydroelectric power, already well-established, expanded from 1,010 gigawatts to 1,400 gigawatts. Together, these renewable sources grew from supplying 19 percent of global electricity in 2010 to 38 percent in 2023. The rate of growth has accelerated particularly in the last five years of this period.',
'{"A": "Renewable energy capacity has decreased over time.", "B": "All renewable energy sources grew substantially, with solar showing the largest proportional increase.", "C": "Only solar energy capacity increased during this period.", "D": "Renewable energy still provides less than 10 percent of global electricity."}',
'B',
'{"rationale": "The data shows all sources increased (solar 40 to 1200 GW, wind 198 to 1000 GW, hydro 1010 to 1400 GW). Solar had the largest proportional increase (30x growth) compared to wind (5x) and hydro (1.4x).", "why_others_wrong": {"A": "All capacity numbers increased", "C": "Wind and hydro also increased", "D": "Renewables reached 38 percent in 2023"}}',
ARRAY['data-interpretation', 'trends', 'renewable-energy']),

('Information & Ideas', 'mcq', 'medium',
'Which conclusion about smartphone usage is best supported by the survey data?',
'A technology use survey of 5,000 adults revealed distinct patterns across age groups. Among 18-34 year olds, 94 percent used smartphones as their primary internet device, compared to 79 percent of 35-54 year olds and 58 percent of those 55 and older. For social media access, 87 percent of 18-34 year olds used smartphones exclusively, while 62 percent of 35-54 year olds and only 41 percent of 55-plus users did so. Computer usage showed an inverse relationship: increasing with age from 35 percent primary computer use among 18-34 year olds to 67 percent among those 55 and older.',
'{"A": "Older adults are more likely than younger adults to use smartphones as their primary internet device.", "B": "Younger age groups show higher rates of smartphone dependency for internet and social media access.", "C": "Social media usage rates are identical across all age groups.", "D": "Computer usage is equally common among all age demographics."}',
'B',
'{"rationale": "The data clearly shows smartphone dependency decreases with age: 94 percent of 18-34 year olds use smartphones as primary device compared to lower percentages in older groups. Social media smartphone use follows the same pattern (87 percent youth vs. 41 percent older adults).", "why_others_wrong": {"A": "Data shows opposite pattern—younger adults have higher smartphone use", "C": "Social media smartphone use varies dramatically by age", "D": "Computer use increases with age, not equal across groups"}}',
ARRAY['data-interpretation', 'survey-analysis', 'demographics']),

('Information & Ideas', 'mcq', 'medium',
'The graph comparing average temperatures across decades most strongly supports which conclusion?',
'A climate research team compiled average global temperature data from 1880 through 2023. Each decade showed temperatures relative to the 1951-1980 baseline. The 1880-1889 decade averaged 0.25 degrees Celsius below baseline. Temperatures gradually rose, reaching baseline level in 1970-1979. The warming accelerated thereafter: 1990-1999 averaged 0.36 degrees above baseline, 2000-2009 reached 0.63 degrees above, 2010-2019 hit 0.93 degrees above, and the early 2020s already show 1.14 degrees above baseline despite being incomplete.',
'{"A": "Global temperatures have remained constant over the past 140 years.", "B": "The rate of temperature increase has accelerated in recent decades.", "C": "The coldest decade on record was the 2000s.", "D": "Temperature changes show no consistent pattern over time."}',
'B',
'{"rationale": "The data shows accelerating warming: it took 90 years (1880s-1970s) to rise 0.25 degrees, then just 30 years (1970s-2000s) to rise another 0.63 degrees, and the following two decades added 0.51 degrees. The increases per decade are getting larger.", "why_others_wrong": {"A": "Temperatures rose from negative 0.25 to positive 1.14 degrees", "C": "2000s were among the warmest, not coldest", "D": "Clear consistent upward pattern is evident"}}',
ARRAY['data-interpretation', 'climate-data', 'trends']),

('Information & Ideas', 'mcq', 'medium',
'What can be inferred about income inequality from the provided data?',
'Economic data from 1980 to 2020 reveals shifting income distribution patterns. In 1980, the top 1 percent of earners held 10 percent of total national income, while the bottom 50 percent held 20 percent. By 2000, these figures had shifted to 16 percent for the top 1 percent and 15 percent for the bottom 50 percent. The 2020 data shows the top 1 percent controlling 20 percent of income while the bottom 50 percent held only 13 percent. Meanwhile, median household income adjusted for inflation grew 28 percent over this period, but income for the top 1 percent grew 175 percent.',
'{"A": "Income inequality decreased between 1980 and 2020.", "B": "The bottom 50 percent of earners increased their share of national income.", "C": "Income gains were distributed unevenly, with the highest earners capturing a growing share.", "D": "All income groups experienced identical percentage growth rates."}',
'C',
'{"rationale": "The data shows the top 1 percent doubled their income share (10 to 20 percent) while the bottom 50 percent saw their share decline (20 to 13 percent). Additionally, top 1 percent income grew 175 percent versus 28 percent for median households—clear uneven distribution.", "why_others_wrong": {"A": "Inequality clearly increased as the gap widened", "B": "Bottom 50 percent share decreased from 20 to 13 percent", "D": "Growth rates varied dramatically (175 vs. 28 percent)"}}',
ARRAY['data-interpretation', 'economic-data', 'inequality']),

('Information & Ideas', 'mcq', 'hard',
'Based on the experimental results, which hypothesis receives the strongest support?',
'Researchers tested whether exercise timing affects sleep quality by having participants exercise at different times. Group A exercised at 7 AM (n equals 50): 82 percent reported good sleep quality, averaging 7.4 hours per night. Group B exercised at 1 PM (n equals 50): 79 percent reported good sleep, averaging 7.2 hours. Group C exercised at 7 PM (n equals 50): 68 percent reported good sleep, averaging 6.8 hours. Group D (control, no structured exercise, n equals 50): 65 percent reported good sleep, averaging 6.5 hours. Statistical analysis found significant differences between morning and evening exercise groups.',
'{"A": "Exercise timing has no effect on sleep quality.", "B": "Any exercise improves sleep equally regardless of timing.", "C": "Morning and afternoon exercise appear more beneficial for sleep than evening exercise.", "D": "Evening exercise produces better sleep outcomes than morning exercise."}',
'C',
'{"rationale": "Morning (82 percent good sleep, 7.4 hours) and afternoon (79 percent, 7.2 hours) groups showed substantially better outcomes than evening (68 percent, 6.8 hours) and control (65 percent, 6.5 hours) groups. Both earlier exercise groups exceeded evening exercise.", "why_others_wrong": {"A": "Clear differences exist between timing groups", "B": "Evening exercise performed worse than morning/afternoon", "D": "Data shows opposite—morning outperformed evening"}}',
ARRAY['data-interpretation', 'research-analysis', 'experimental-design']),

('Information & Ideas', 'mcq', 'hard',
'The correlation data most strongly suggests which relationship between variables?',
'A public health study examined relationships between neighborhood characteristics and health outcomes across 500 urban areas. Researchers found a negative 0.71 correlation between green space access and stress-related illness rates. They observed a negative 0.58 correlation between walkability scores and obesity rates. Air quality showed a negative 0.82 correlation with respiratory illness rates. However, median income showed only a 0.23 correlation with health outcomes when controlling for these environmental factors, suggesting neighborhood design matters more than wealth alone.',
'{"A": "Wealthier neighborhoods have better health outcomes regardless of other factors.", "B": "Environmental factors show stronger associations with health than income alone.", "C": "Green space has no measurable effect on health outcomes.", "D": "Walkability is unrelated to obesity rates in the data."}',
'B',
'{"rationale": "Environmental factors show strong negative correlations with poor health outcomes (green space negative 0.71, walkability negative 0.58, air quality negative 0.82) while income shows weak correlation (0.23) when controlling for environment. The passage explicitly states environment matters more than wealth.", "why_others_wrong": {"A": "Income showed weak correlation when controlling for environment", "C": "Green space showed strong negative 0.71 correlation", "D": "Walkability showed negative 0.58 correlation with obesity"}}',
ARRAY['data-interpretation', 'correlation-analysis', 'public-health']),

('Information & Ideas', 'mcq', 'hard',
'Which conclusion about educational outcomes is best supported by the longitudinal data?',
'A 20-year study tracked educational achievement across three cohorts of schools implementing different approaches. Traditional schools (40 schools, 12,000 students) maintained conventional lecture-based instruction. Project-based schools (35 schools, 10,500 students) emphasized collaborative problem-solving. Technology-integrated schools (25 schools, 7,500 students) blended both approaches with personalized digital tools. At year 5, test scores differed minimally across groups. By year 10, project-based schools showed 12 percent higher critical thinking scores but 3 percent lower standardized test performance. Technology-integrated schools demonstrated 15 percent higher problem-solving scores, 8 percent higher standardized test scores, and 20 percent better engagement metrics by year 20. Teacher satisfaction increased 35 percent in technology-integrated schools versus 8 percent in traditional schools.',
'{"A": "Traditional lecture-based instruction produces the best long-term outcomes.", "B": "Technology-integrated approaches show promise across multiple outcome measures over time.", "C": "Project-based learning reduces all forms of academic achievement.", "D": "School approach makes no difference in educational outcomes."}',
'B',
'{"rationale": "Technology-integrated schools showed improvements across multiple dimensions: problem-solving (15 percent higher), standardized tests (8 percent higher), engagement (20 percent higher), and teacher satisfaction (35 percent increase). These diverse positive outcomes across 20 years support the promise of this approach.", "why_others_wrong": {"A": "Traditional schools showed no particular advantages", "C": "Project-based improved critical thinking despite slightly lower standardized scores", "D": "Clear differences emerged, especially by year 20"}}',
ARRAY['data-interpretation', 'longitudinal-studies', 'education']),

('Information & Ideas', 'mcq', 'easy',
'According to the chart, which energy source produces the least carbon dioxide per kilowatt-hour?',
'A comparative analysis examined carbon dioxide emissions across electricity generation methods measured in grams per kilowatt-hour. Coal-fired power plants produced 820 grams. Natural gas plants generated 490 grams. Solar photovoltaic systems produced 48 grams (accounting for manufacturing). Wind turbines generated 26 grams (including production and installation). Nuclear power produced 16 grams (across its full lifecycle). Hydroelectric dams averaged 34 grams. These figures include not just operational emissions but also construction and decommissioning impacts.',
'{"A": "Coal", "B": "Natural gas", "C": "Solar", "D": "Nuclear"}',
'D',
'{"rationale": "Nuclear produces 16 grams per kilowatt-hour, the lowest value listed. Wind is second at 26 grams, and hydroelectric third at 34 grams.", "why_others_wrong": {"A": "Coal produces the most at 820 grams", "B": "Natural gas produces 490 grams", "C": "Solar produces 48 grams, more than nuclear, wind, and hydro"}}',
ARRAY['data-interpretation', 'energy-comparison', 'emissions']),

('Information & Ideas', 'mcq', 'medium',
'The medication trial data best supports which interpretation?',
'A pharmaceutical company tested a new medication against a placebo in treating chronic pain. The treatment group (n equals 200) received the medication: 62 percent reported significant pain reduction, 24 percent reported moderate reduction, 14 percent reported no change. The placebo group (n equals 200) received inactive pills: 28 percent reported significant reduction, 31 percent moderate reduction, 41 percent no change. Side effects occurred in 18 percent of treatment group versus 8 percent of placebo group. The treatment group showed statistically significant improvement (p less than 0.001) compared to placebo.',
'{"A": "The medication shows no advantage over placebo for pain reduction.", "B": "The medication demonstrates statistically significant benefits despite some side effects.", "C": "Placebo produced better pain reduction than the medication.", "D": "Side effects occur equally in both groups."}',
'B',
'{"rationale": "Treatment group showed substantially better outcomes: 62 percent significant reduction versus placebo 28 percent, with statistical significance (p less than 0.001). Side effects were higher (18 vs. 8 percent) but benefits outweighed this, demonstrating significant advantage despite side effects.", "why_others_wrong": {"A": "Treatment showed clear statistical advantage", "C": "Treatment group outcomes were superior across all measures", "D": "Side effects were higher in treatment group (18 vs. 8 percent)"}}',
ARRAY['data-interpretation', 'clinical-trials', 'statistics']),

('Information & Ideas', 'mcq', 'hard',
'The demographic data most strongly challenges which common assumption?',
'Census data analysis of US household structures from 1970 to 2020 revealed significant shifts. In 1970, married couples with children represented 40 percent of households, single-person households 17 percent, and unmarried partners 1 percent. By 2020, married couples with children dropped to 18 percent, single-person households rose to 28 percent, and unmarried partners reached 7 percent. Meanwhile, multi-generational households (grandparents, parents, and children) increased from 12 percent to 20 percent. The median household size decreased from 3.1 to 2.5 people. These changes reflected later marriage ages, increased divorce rates, longer life expectancies, and economic pressures driving multiple generations to live together.',
'{"A": "The traditional nuclear family remains the dominant household type.", "B": "Multi-generational living is becoming less common over time.", "C": "Single-person households represent a shrinking demographic.", "D": "Household structures are becoming more diverse."}',
'A',
'{"rationale": "The data directly challenges the assumption that nuclear families (married couples with children) remain dominant. This household type dropped from 40 to 18 percent while other forms grew, meaning nuclear families are no longer the majority or dominant type.", "why_others_wrong": {"B": "Multi-generational living increased from 12 to 20 percent", "C": "Single-person households grew from 17 to 28 percent", "D": "This is supported, not challenged—diversity clearly increased"}}',
ARRAY['data-interpretation', 'demographic-trends', 'social-change']),

('Information & Ideas', 'mcq', 'hard',
'Based on the agricultural yield data, which factor appears most strongly associated with productivity increases?',
'Researchers analyzed corn yield data across 1,000 farms over 10 years, measuring various factors. Farms using precision agriculture technology averaged 180 bushels per acre, while those without averaged 145 bushels. Farms with soil health programs averaged 175 bushels versus 150 for those without. Organic farms averaged 140 bushels while conventional farms averaged 165. When researchers examined farms using both precision technology AND soil health programs (n equals 150), yields reached 195 bushels per acre. The highest yields of 205 bushels occurred at conventional farms combining both practices (n equals 50).',
'{"A": "Organic farming produces the highest yields.", "B": "Soil health programs alone determine productivity.", "C": "Combining precision technology with soil health practices produces optimal results.", "D": "Individual farming practices have no measurable effect on yields."}',
'C',
'{"rationale": "The data shows combining practices produced the best results: farms using both precision technology and soil health programs achieved 195 bushels, and conventional farms with both reached 205 bushels—higher than any single practice alone. This demonstrates the power of combining approaches.", "why_others_wrong": {"A": "Organic farms had the lowest yields at 140 bushels", "B": "Soil health alone (175 bushels) was exceeded by combined approaches", "D": "Clear differences exist between different practices"}}',
ARRAY['data-interpretation', 'agricultural-data', 'multivariable-analysis']);