-- FINAL COMPLETION: 58 remaining questions across math domains
INSERT INTO public.sat_questions (domain, question_type, difficulty, question_text, choices, correct_answer, explanation, tags) VALUES
-- Algebra (18 questions)
('Algebra', 'mcq', 'easy', 'Solve: x - 7 = 12', '["5", "19", "21", "84"]', '19', 'Adding 7 to both sides: x = 19.', ARRAY['equations', 'addition']),
('Algebra', 'mcq', 'medium', 'Factor completely: 3x² - 12', '["3(x² - 4)", "3(x - 2)(x + 2)", "(3x - 6)(x + 2)", "3x(x - 4)"]', '3(x - 2)(x + 2)', 'Factor out 3, then use difference of squares.', ARRAY['factoring', 'gcf']),
('Algebra', 'mcq', 'hard', 'If f(x) = 2x + 1, what is the inverse function value when y = 7?', '["2", "3", "4", "5"]', '3', 'Solving for x: x = (y-1)/2. When y = 7, x = 3.', ARRAY['inverse-functions', 'notation']),
('Algebra', 'mcq', 'easy', 'What is the x-intercept of y = 2x - 8?', '["2", "4", "6", "8"]', '4', 'Set y = 0: x = 4.', ARRAY['intercepts', 'linear']),
('Algebra', 'mcq', 'medium', 'Solve: |x - 5| = 3', '["x = 2 or 8", "x = -2 or -8", "x = 3 or 5", "x = 5"]', 'x = 2 or 8', 'x - 5 = 3 gives x = 8, or x - 5 = -3 gives x = 2.', ARRAY['absolute-value', 'equations']),
('Algebra', 'mcq', 'hard', 'What is the discriminant of 2x² + 5x - 3 = 0?', '["1", "19", "25", "49"]', '49', 'Discriminant = b² - 4ac = 25 - 4(2)(-3) = 25 + 24 = 49.', ARRAY['discriminant', 'quadratics']),
('Algebra', 'mcq', 'easy', 'What is 6/2(1+2)?', '["1", "9", "12", "18"]', '9', 'Order of operations: 6/2(3) = 3(3) = 9.', ARRAY['pemdas', 'operations']),
('Algebra', 'mcq', 'medium', 'If 3 to the x power = 27, what is x?', '["2", "3", "9", "27"]', '3', '3 cubed = 27, so x = 3.', ARRAY['exponential-equations', 'same-base']),
('Algebra', 'mcq', 'hard', 'What is the axis of symmetry for y = 2x² - 12x + 5?', '["x = -3", "x = 3", "x = -6", "x = 6"]', 'x = 3', 'Axis formula: x = -b/(2a) = 12/4 = 3.', ARRAY['parabolas', 'axis']),
('Algebra', 'mcq', 'easy', 'Simplify: 2x + 3x - x', '["4x", "5x", "6x", "x"]', '4x', 'Combining: 2x + 3x - x = 4x.', ARRAY['combining-terms', 'basic']),
('Algebra', 'mcq', 'medium', 'If the slope is -2 passing through (3, 4), what is the y-intercept?', '["2", "4", "8", "10"]', '10', 'Using y = mx + b: 4 = -2(3) + b, so b = 10.', ARRAY['slope-intercept', 'linear']),
('Algebra', 'mcq', 'hard', 'Solutions to x² + 4x - 21 = 0 are:', '["x = -7, 3", "x = 7, -3", "x = -3, 7", "x = 3, -7"]', 'x = -7, 3', 'Factoring: (x+7)(x-3) = 0.', ARRAY['quadratics', 'factoring']),
('Algebra', 'mcq', 'easy', 'What is negative of negative 5?', '["- 5", "5", "0", "10"]', '5', 'Double negative is positive.', ARRAY['integers', 'negatives']),
('Algebra', 'mcq', 'medium', 'Simplify: square root of 48', '["4√3", "3√4", "6√2", "12√2"]', '4√3', 'Breaking down: √48 = √(16×3) = 4√3.', ARRAY['radicals', 'simplification']),
('Algebra', 'mcq', 'hard', 'If log base 3 of (x times (x+2)) = 3, what is x?', '["3", "5", "7", "9"]', '5', 'Converting: x(x+2) = 27, solving gives x = 5.', ARRAY['logarithms', 'properties']),
('Algebra', 'mcq', 'easy', 'What is 0.75 as a simple fraction?', '["75/100", "3/4", "7/5", "15/20"]', '3/4', '0.75 = 3/4 in simplest form.', ARRAY['fractions', 'conversion']),
('Algebra', 'mcq', 'medium', 'Simplify: √(x²)', '["x", "|x|", "x²", "2x"]', '|x|', 'Square root of x² is absolute value of x.', ARRAY['radicals', 'absolute-value']),
('Algebra', 'mcq', 'hard', 'Vertex of y = -2(x+1)² - 3 is:', '["(1, -3)", "(-1, -3)", "(1, 3)", "(-1, 3)"]', '(-1, -3)', 'Vertex form shows (h, k) = (-1, -3).', ARRAY['parabolas', 'vertex']),

-- Problem Solving & Data Analysis (20 questions)
('Problem Solving & Data Analysis', 'mcq', 'easy', 'Convert 2.5 hours to minutes.', '["120", "125", "140", "150"]', '150', '2.5 times 60 = 150 minutes.', ARRAY['unit-conversion', 'time']),
('Problem Solving & Data Analysis', 'mcq', 'medium', 'Mean = 50, SD = 5. What range contains 95% of data in normal distribution?', '["40-60", "45-55", "35-65", "30-70"]', '40-60', 'Within 2 standard deviations: 50 ± 10.', ARRAY['normal-distribution', 'empirical-rule']),
('Problem Solving & Data Analysis', 'mcq', 'hard', 'Which introduces most bias: surveying gym members about exercise?', '["Random sampling", "Convenience sampling", "Stratified sampling", "Systematic sampling"]', 'Convenience sampling', 'Gym members already exercise, creating selection bias.', ARRAY['sampling-bias', 'methods']),
('Problem Solving & Data Analysis', 'mcq', 'easy', 'If 40 of 200 students are absent, what percent?', '["15%", "20%", "25%", "30%"]', '20%', '40/200 = 0.20 = 20%.', ARRAY['percentages', 'basic']),
('Problem Solving & Data Analysis', 'mcq', 'medium', 'Two dice rolled. Probability sum = 7?', '["1/12", "1/9", "1/6", "1/4"]', '1/6', '6 ways to get 7 out of 36 outcomes = 1/6.', ARRAY['probability', 'dice']),
('Problem Solving & Data Analysis', 'mcq', 'hard', 'Regression line y = 2x + 5 with r² = 0.81. What % variance explained?', '["19%", "81%", "90%", "95%"]', '81%', 'R² directly represents variance explained.', ARRAY['regression', 'r-squared']),
('Problem Solving & Data Analysis', 'mcq', 'easy', 'A number is 20% of 150. What is it?', '["20", "25", "30", "35"]', '30', '0.20 times 150 = 30.', ARRAY['percentages', 'calculation']),
('Problem Solving & Data Analysis', 'mcq', 'medium', 'Normal distribution: mean 100, SD 15. What % between 85 and 115?', '["50%", "68%", "95%", "99%"]', '68%', 'One SD from mean contains 68%.', ARRAY['normal-distribution', 'rule']),
('Problem Solving & Data Analysis', 'mcq', 'hard', 'Relative risk = 2.5 for exposed vs unexposed. This means:', '["2.5 times the risk", "2.5% risk", "25% increase", "Risk down 2.5x"]', '2.5 times the risk', 'RR = 2.5 means exposed group has 2.5 times the risk.', ARRAY['relative-risk', 'epidemiology']),
('Problem Solving & Data Analysis', 'mcq', 'easy', 'Gas is $3 per gallon. Cost for 12 gallons?', '["$30", "$33", "$36", "$39"]', '$36', '3 times 12 = 36.', ARRAY['multiplication', 'money']),
('Problem Solving & Data Analysis', 'mcq', 'medium', 'Population was 8000, grew to 10000. Percent increase?', '["20%", "25%", "30%", "35%"]', '25%', 'Increase = 2000/8000 = 0.25 = 25%.', ARRAY['percent-change', 'calculation']),
('Problem Solving & Data Analysis', 'mcq', 'hard', 'Odds 3:7. What is probability of winning?', '["3/7", "3/10", "7/10", "3/4"]', '3/10', 'Odds 3:7 means 3 out of 10 total.', ARRAY['odds-vs-probability', 'conversion']),
('Problem Solving & Data Analysis', 'mcq', 'easy', 'Volume of box: length 5, width 3, height 4?', '["12", "20", "35", "60"]', '60', '5 times 3 times 4 = 60.', ARRAY['volume', 'rectangular-prism']),
('Problem Solving & Data Analysis', 'mcq', 'medium', 'Mode is 15, appearing 5 times. What does this mean?', '["15 is mean", "15 is median", "15 most frequent", "15 is range"]', '15 most frequent', 'Mode is the most frequently occurring value.', ARRAY['mode', 'definition']),
('Problem Solving & Data Analysis', 'mcq', 'hard', 'Confidence interval narrower when:', '["Sample size down", "Confidence up", "Sample size up", "Variability up"]', 'Sample size up', 'Larger samples give more precise estimates.', ARRAY['confidence-intervals', 'precision']),
('Problem Solving & Data Analysis', 'mcq', 'easy', 'Percent decrease from 80 to 60?', '["20%", "25%", "30%", "33%"]', '25%', 'Decrease = 20/80 = 0.25 = 25%.', ARRAY['percent-change', 'decrease']),
('Problem Solving & Data Analysis', 'mcq', 'medium', 'Scatterplot shows r = 0.95. This indicates:', '["Weak positive", "Strong positive", "Weak negative", "No correlation"]', 'Strong positive', 'r near 1 indicates strong positive correlation.', ARRAY['correlation', 'strength']),
('Problem Solving & Data Analysis', 'mcq', 'hard', 'Sample mean 50, population SD 10, n=100. Standard error is:', '["0.1", "1", "10", "100"]', '1', 'SE = SD/√n = 10/√100 = 10/10 = 1.', ARRAY['standard-error', 'sampling']),
('Problem Solving & Data Analysis', 'mcq', 'easy', 'Average of 20, 30, 40?', '["25", "30", "35", "40"]', '30', 'Sum = 90, divided by 3 = 30.', ARRAY['mean', 'average']),
('Problem Solving & Data Analysis', 'mcq', 'medium', 'Probability of rolling 6 on fair die twice?', '["1/36", "1/12", "1/6", "1/3"]', '1/36', '(1/6) times (1/6) = 1/36.', ARRAY['probability', 'independent']),

-- Geometry (10 questions)
('Geometry', 'mcq', 'easy', 'What is the area of a rectangle with length 8 and width 5?', '["13", "26", "40", "80"]', '40', 'Area = length times width = 8 times 5 = 40.', ARRAY['area', 'rectangles']),
('Geometry', 'mcq', 'medium', 'Circle has radius 5. What is its circumference?', '["5π", "10π", "25π", "50π"]', '10π', 'Circumference = 2πr = 2π(5) = 10π.', ARRAY['circles', 'circumference']),
('Geometry', 'mcq', 'hard', 'Right triangle has legs 6 and 8. What is the hypotenuse?', '["7", "10", "12", "14"]', '10', 'Pythagorean theorem: √(36+64) = √100 = 10.', ARRAY['pythagorean-theorem', 'right-triangles']),
('Geometry', 'mcq', 'easy', 'Area of triangle with base 10 and height 6?', '["16", "30", "60", "120"]', '30', 'Area = (1/2) times base times height = (1/2)(10)(6) = 30.', ARRAY['area', 'triangles']),
('Geometry', 'mcq', 'medium', 'Volume of cylinder with radius 3 and height 10?', '["30π", "60π", "90π", "300π"]', '90π', 'Volume = πr²h = π(9)(10) = 90π.', ARRAY['volume', 'cylinders']),
('Geometry', 'mcq', 'hard', 'Two angles are supplementary. One is 65 degrees. What is the other?', '["25", "115", "125", "295"]', '115', 'Supplementary angles sum to 180. Other = 180 - 65 = 115.', ARRAY['angles', 'supplementary']),
('Geometry', 'mcq', 'easy', 'Perimeter of square with side 7?', '["14", "21", "28", "49"]', '28', 'Perimeter = 4 times side = 4 times 7 = 28.', ARRAY['perimeter', 'squares']),
('Geometry', 'mcq', 'medium', 'Circle area is 25π. What is radius?', '["5", "10", "12.5", "25"]', '5', 'Area = πr², so 25π = πr², thus r² = 25, r = 5.', ARRAY['circles', 'area']),
('Geometry', 'mcq', 'hard', 'In 30-60-90 triangle, if short leg is 4, what is hypotenuse?', '["4", "4√3", "8", "8√3"]', '8', 'In 30-60-90 triangle, hypotenuse = 2 times short leg = 8.', ARRAY['special-triangles', '30-60-90']),
('Geometry', 'mcq', 'easy', 'Sum of angles in a triangle?', '["90°", "180°", "270°", "360°"]', '180°', 'Triangle angles always sum to 180 degrees.', ARRAY['angles', 'triangles']),

-- Advanced Math (10 questions)
('Advanced Math', 'mcq', 'easy', 'Simplify: x⁰', '["0", "1", "x", "undefined"]', '1', 'Any non-zero number to the zero power equals 1.', ARRAY['exponents', 'zero-power']),
('Advanced Math', 'mcq', 'medium', 'If f(x) = x³, what is f(-2)?', '["- 8", "- 6", "6", "8"]', '- 8', '(-2)³ = -8.', ARRAY['cubic-functions', 'evaluation']),
('Advanced Math', 'mcq', 'hard', 'Solve: x³ = 64', '["2", "4", "8", "16"]', '4', 'Cube root of 64 is 4.', ARRAY['cubic-equations', 'roots']),
('Advanced Math', 'mcq', 'easy', 'What is i²? (where i is imaginary unit)', '["- 1", "0", "1", "i"]', '- 1', 'By definition, i² = -1.', ARRAY['complex-numbers', 'imaginary']),
('Advanced Math', 'mcq', 'medium', 'Expand: (x + 2)²', '["x² + 4", "x² + 2x + 4", "x² + 4x + 4", "x² + 4x + 2"]', 'x² + 4x + 4', 'Perfect square: (a+b)² = a² + 2ab + b².', ARRAY['binomial-squares', 'expansion']),
('Advanced Math', 'mcq', 'hard', 'If sin(θ) = 3/5 and θ is acute, what is cos(θ)?', '["3/5", "4/5", "5/3", "5/4"]', '4/5', 'Using Pythagorean identity: cos² = 1 - (9/25) = 16/25, so cos = 4/5.', ARRAY['trigonometry', 'pythagorean-identity']),
('Advanced Math', 'mcq', 'easy', 'Domain of f(x) = √x is:', '["All real numbers", "x ≥ 0", "x > 0", "x ≤ 0"]', 'x ≥ 0', 'Square root requires non-negative input.', ARRAY['domain', 'square-roots']),
('Advanced Math', 'mcq', 'medium', 'Period of y = sin(2x) is:', '["π/2", "π", "2π", "4π"]', 'π', 'Period of sin(bx) = 2π/b = 2π/2 = π.', ARRAY['trigonometry', 'period']),
('Advanced Math', 'mcq', 'hard', 'Asymptote of y = 1/(x-3) + 2 is:', '["x = 3, y = 2", "x = -3, y = -2", "x = 2, y = 3", "x = 3 only"]', 'x = 3, y = 2', 'Vertical asymptote at x = 3, horizontal at y = 2.', ARRAY['rational-functions', 'asymptotes']),
('Advanced Math', 'mcq', 'easy', 'Simplify: x³/x²', '["x", "x⁵", "1", "x⁶"]', 'x', 'Dividing powers: x³⁻² = x¹ = x.', ARRAY['exponents', 'division']);