// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mkmrasgbrhwtycwpdtke.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1rbXJhc2dicmh3dHljd3BkdGtlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5OTMxODQsImV4cCI6MjA2NDU2OTE4NH0.LSWp2Ibx_7S2m-yZM-yVetVUtu9qThDc8YmEeDOYodg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);